package com.jemmy.hello.spring.boot.dao;

import com.jemmy.hello.spring.boot.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    /**
     * 根据商品id查找购物车
     */
    Cart findProductByUserId(@Param("userId") Integer userId, @Param("productId") Integer productId);

    /**
     * 根据商品数量
     */
    int updateQuantity(@Param("userId") Integer userId, @Param("productId") Integer productId, @Param("count") Integer count);

    /**
     * 根据用户id查询未选中的个数
     */
    int selectUnCheckedCountByUserId(@Param("userId") Integer userId);

    /**
     * 根据用户id和商品id查询选中状态
     */
    int selectCheckedByUserIdAndProductId(@Param("userId") Integer userId, @Param("productId") Integer productId);

    /**
     * 根据用户Id查询
     */
    List<Cart> selectByUserId(@Param("userId") Integer userId);

    /**
     * 全选或取消全选
     */
    int updateAllChecked(@Param("userId") Integer userId, @Param("check") Integer check);

    /**
     * 全选或取消全选
     */
    int updateChecked(@Param("userId") Integer userId, @Param("productId") Integer productId, @Param("check") Integer check);

    /**
     * 删除全部商品
     */
    int deleteAllByUserId(@Param("userId") Integer userId);

    /**
     * 删除商品
     */
    int deleteByUserIdAndProductId(@Param("userId") Integer userId, @Param("productId") Integer productId);

    /**
     * 查找选中商品
     */
    List<Cart> findCartByUserIdAndChecked(@Param("userId") Integer userId);

    /**
     * 根据多个id删除
     */
    int deleteByIds(@Param("ids") List<Integer> ids);
}