package com.jemmy.hello.spring.boot.dao;

import com.jemmy.hello.spring.boot.pojo.LoginUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_loginuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_loginuser
     *
     * @mbg.generated
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_loginuser
     *
     * @mbg.generated
     */
    LoginUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_loginuser
     *
     * @mbg.generated
     */
    List<LoginUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_loginuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginUser record);

    /**
     * 插入登录用户
     */
    int putLoginUser(@Param("username") String username);

    /**
     * 根据用户名查询登录状态
     */
    LoginUser selectByUsername(@Param("username") String username);

    /**
     * 根据状态查询
     */
    List<LoginUser> selectByStatus(@Param("status") Integer status);

    /**
     * 消除登录状态
     * update *** set
     */
    int allSignOut();

    /**
     * 注销
     */
    int signOutByUsername(@Param("username") String username);
}