package com.jemmy.hello.spring.boot.dao;

import com.jemmy.hello.spring.boot.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jemmy_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据用户名查找
     */
    User findByUsername(@Param("username") String username);

    /**
     * 根据用户名和密码查找
     */
    User findByUsernameAndPassword(@Param("username") String username, @Param("password") String password);

    /**
     * 根据手机查找
     */
    int findByPhone(@Param("phone") String phone);

    /**
     * 根据id更改密码
     */
    int changePasswordById(@Param("id") Integer id, @Param("now") String now);

    /**
     * 根据id更改手机号
     */
    int changePhoneById(@Param("userId") Integer id, @Param("newphone") String newPhone);

}