spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/business?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
server:
  port: 8081

mybatis:
  mapper-locations: classpath*:com/jemmy/hello/spring/boot/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

alipay:
  appid: 2016102400748346
  pid: 2088102180830201
  target_id: ""
  rsa2_private: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDLJob8IFeEq6Gs6lpf1VeQ9iYX0/reHgFrGF4NP1UB/0qYLDHw2ow1IY0gfMKpGOWtI2xR7oavyrM2PFCOWuE1ivxxW4VR7r5/uBxErXNx7VHR3RzzFAfpJbiQABjc4pC50336jAOG/FyaFtspPJje8Cf1uwVUX1/6DPtiCX27kHGvIkckOXwfjMwqG7D5cRQxTfBfawLJ9Ykw4IxCmfrEhCdffQn1RkmzYyH2a8wy486pRPMY47YK5Mzgktl4aDKa00GuXiFDig5+fyeAzj+kB6Ea25iqudL+97Dg+oOnNqkgqtrOHj5ukVbfDXwlNx6dEEoAEvJyEO4ENNcy1U41AgMBAAECggEBAJPB4v4wu9cYSpCNJ8x6TKV4Ez7ThKzXYCq333h9LuQz/dpukqhfHQlr7MzLUX5SSINEt31kIvxrTyvMdL8FpLYf7/q3GWH9ZvtYOt9M1SHw/cjJrUuzrwlJ0VKTb4IBHEi8Ze28trgQh33fz+nPVFUakcXuEDNM527k0FZ/Fr87RPtkxuKPax3+/5Rr/zKV1ghtQPMNpOzXurSNVH9Y8FuLkP/uvVqhEUyGwvPRDZ2UqQ/ArqSw4f/M7TgMCh6QDJX1GdnKlUeQTQL46WfE3hYp7DW8y0EZ/Sva2pGDtH428f/g/RNLxcFI3bkMRbo1yCYbH6AreokLgoj9PO5kwUUCgYEA79f5Gu7UDtdnwN9RXLo5MsuIEE2j4u1Hrqf32Dji7YOWdM05Vlfdhs5RwCugIgbT/JxrTrdp1xN3C4cbfd68w5qklPSSrzO4So4aNxQNRFEuhCHfCIRmLF+uAK+0fpTQSO6Jd/fCd6m3z0wKuf8mc8gaQFUHH1yR5VIRC2pTqU8CgYEA2NXK6XSnnwRCgmucwDxVhzaRvEy2Jew9VNk4e6+hu2tYiYQPhlgcNvM5dczFnBkG5YFxFHaIBM3VejdUUbW0B/dDcZ4bYu06y4KWa/i8oeBR9zE7lkcy56fSUxdeo3j4cagUVJZu493TM/chHpswijNlZ19mnbEtvzfWKMAJ5zsCgYEA7Kf0emjSAVr2W09/Hrn5mm9N8JhLb6yloGbInSd0ctv2Z4XgX5wPT+bgr3fcZ/bI0WceUuuTmc7xFgTYUZioNXGvl/LDkfC8lYQlxdcZSCG6flJVmjfaAUrfjHnS5Vu9MVl9d0yXLC/g2MC1jNWAgZoenP/JKV7T7qzNeLAPoO0CgYEAsm3TKKKm4HKX7ExzU7kSRE7CQ+n4JWKt4WlSUm1nMBuYYqi6Qbm1lf41tVsI7Xemtir7C3SyXwml9okbKJXWDIwLAq6xKInATQErmLO5PZeiuz/XIcV6/SebKmbbqLd98cD24dhcbcP27RcaON5JZh/+/L6DaZYH6AchgqzsOUsCgYEAiIvKb1UaYntBNwMgRsMv0H6jFdCVCuneKb/F0wDM6agipIZeBlDO5D1THI+d4Z5LKW8/2RAaX8R1NKo9sUgA+lTrKez/NFEM29qX9dl/YZGBPqXB40M9orre09ekoZlqBk/6nMEFDBD67R0Y6B6qbJKXH2RR6VBAKWdhsDX175c=
  notify_url: http://139.196.39.188:8081/portal/pay/callback.do
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgEzJn9nBRcJ1dEIWWmu1SkBxSAM/aHVm1iDaiXS4Hw6he9Ixl0crv28miDyTBlpvcPXG0g8up92haCmNc3HAhRmOIzxq5kZwVZeDnKL8rdDI5gRrUR8l7yK9Trb4M5ag7q1Lf93++Ze+sHOS3bs3Oo1ajym1YEVxOa01+LgXR1E4E7LlVjeO2Xyh5VVBa/MI9YcJlf1473X/a/n52HGq4fBZq6DlAnkIugBGvFxUBzkPcybJ2OAJkZ+M/Y9HkzWV2M2l9glA6TbGhBoZHMap+pg/Wp2NNydJSyzccAWFlsDxeoPoe8pTBNDKVLK+wu3RiBWCII4pO5hn881kTG8WnwIDAQAB