spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/business?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
server:
  port: 8080

mybatis:
  mapper-locations: classpath*:com/jemmy/hello/spring/boot/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml