package com.jemmy.hello.spring.boot.pojo;

public class LoginUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jemmy_loginuser.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jemmy_loginuser.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jemmy_loginuser.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jemmy_loginuser.id
     *
     * @return the value of jemmy_loginuser.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jemmy_loginuser.id
     *
     * @param id the value for jemmy_loginuser.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jemmy_loginuser.username
     *
     * @return the value of jemmy_loginuser.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jemmy_loginuser.username
     *
     * @param username the value for jemmy_loginuser.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jemmy_loginuser.status
     *
     * @return the value of jemmy_loginuser.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jemmy_loginuser.status
     *
     * @param status the value for jemmy_loginuser.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}